# Generated by Django 4.2.2 on 2023-07-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
