# Generated by Django 4.2.2 on 2023-07-24 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_rename_user_posts_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post', to='network.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='likedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
