# Generated by Django 4.2.2 on 2023-07-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_price_alter_listing_url_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_close',
            field=models.BooleanField(default=True),
        ),
    ]
