# Generated by Django 4.2.2 on 2023-07-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=130)),
                ('content', models.TextField()),
                ('author', models.TextField(max_length=120)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
