# Generated by Django 4.2.2 on 2023-07-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=120),
        ),
    ]
